import React from 'react';
import { GitCompare, Check } from 'lucide-react';

export default function DiffViewer({ diff }) {
  if (!diff) return null;

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl backdrop-blur">
      <div className="flex items-center space-x-2.5 mb-3">
        <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
          <GitCompare className="w-4 h-4" />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-slate-200 uppercase tracking-wider">
            Verified Git Diff
          </h3>
          <p className="text-xs text-slate-400">Surgical modifications generated by the agent</p>
        </div>
      </div>

      <div className="bg-slate-950 rounded-xl border border-slate-800/80 p-4 font-mono text-[11px] overflow-x-auto max-h-64">
        {diff.trim() ? (
          <pre className="text-slate-300 whitespace-pre leading-relaxed">
            {diff.split('\n').map((line, idx) => {
              let color = 'text-slate-400';
              if (line.startsWith('+') && !line.startsWith('+++')) color = 'text-emerald-400 bg-emerald-500/5';
              else if (line.startsWith('-') && !line.startsWith('---')) color = 'text-rose-400 bg-rose-500/5';
              else if (line.startsWith('@@')) color = 'text-indigo-400';

              return (
                <div key={idx} className={`${color} px-1.5 py-0.5 rounded`}>
                  {line}
                </div>
              );
            })}
          </pre>
        ) : (
          <div className="text-slate-600">// Clean working tree: all modifications verified and committed.</div>
        )}
      </div>
    </div>
  );
}
